---
# tasks file for roles/opensuse/confignagios

- name: Configure the nagios
  become: yes
  command: ./configure --with-command-group=nagcmd --with-command-group=nagcmd --with-httpd_conf=/etc/httpd/conf.d
  args:
    chdir: /downloads/nagios-4.2.1

- name: Clean nagios directory
  become: yes
  make:
    chdir: /downloads/nagios-4.2.1
    target: clean

- name: Install init script
  become: yes
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-init

- name: Install config in nagios-4.2.1
  become: yes
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-config

- name: Install commandmode in nagios-4.2.1
  become: yes
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-commandmode

- name: Install nagios web interface
  become: yes
  make:
    chdir: /downloads/nagios-4.2.1
    target: install-webconf

- name: Enable apache rewrite
  shell:  'a2enmod rewrite cgi'

- name: install python for htpasswd
  become: yes
  zypper:
    name: python3-pip
    state: latest

- name: Install htpasswd module
  become: yes
  pip:
    name: passlib
    state: latest

- name: Create nagios admin account
  become: yes
  htpasswd:
    path: /usr/local/nagios/etc/htpasswd.users
    name: nagiosadmin
    password: '{{ nagadminpass }}'
    crypt_scheme: sha256_crypt

- name: Restarting apache
  become: yes
  service:
    name: apache2
    state: reloaded

- name: start apache
  become: yes
  service:
    name: apache2
    state: started

- name: Start nagios service
  become: yes
  service:
    name: nagios
    state: started
