---
# tasks file for roles/centos-setup

  - name: Install httpd
    become: yes
    yum:
      name: httpd
      state: latest
      update_cache: yes


  - name: Change state of firewall
    become: yes
    service:
      name: firewalld
      state: stopped
      enabled: no

  - name: Creating domain directory
    become: yes
    file:
      path: /var/www/html/quiz32
      state: directory
      owner: root
      group: root

  - name: chown quiz32
    become: yes
    shell: chown apache:apache -R /var/www/html/quiz32

  - name: Creating sites-available in httpd
    become: yes
    file:
      path: /etc/httpd/sites-available
      state: directory
      owner: gjgerandoy-tip
      group: gjgerandoy-tip

  - name: Creating sites-enabled in httpd
    become: yes
    file:
      path: /etc/httpd/sites-enabled
      state: directory
      owner: gjgerandoy-tip
      group: gjgerandoy-tip

  - name: Change sudo vi conf
    become: yes
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      line: 'IncludeOptional sites-enabled/*.conf'
      insertafter: .*conf"

  - name: copy file inside the conf
    become: yes
    copy:
      src: /etc/httpd/sites-available/quiz32.com.conf
      remote_src: yes
      dest: /etc/httpd/sites-enabled/quiz32.com.conf

  - name: Create index.html
    become: yes
    copy:
      content: "<h1> Quiz 3.2 12/19/2020 </h1>"
      dest: /var/www/html/quiz32/index.html
    register: apache_index

  - name: Test PHP
    become: yes
    copy:
      content: "<h1> Quiz 3.2 PHP 12/19/2020 </h1>"
      dest: /var/www/html/quiz32/info.php
    
  - name: Restart apache2
    become: yes
    service:
      name: httpd
      state: restarted
      enabled: yes
