---
# tasks file for roles/centos/elk

- name: Add the gpg key
  become: yes
  command: sudo rpm --import https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add the elasticsearch
  become: yes
  copy:
    src: centos/elasticsearch.repo
    dest: /etc/yum.repos.d/

- name: Update the centos
  become: yes
  dnf:
    update_cache: yes

- name: Install the elasticsearch
  become: yes
  dnf:
    name: elasticsearch
    state: present

- name: Update the config file to allow outside access
  become: yes
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: 127.0.0.1'

- name: Update the port in the config file
  become: yes
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'http.port:'
    line: 'http.port: 9200'

- name: Start the elasticsearch
  become: yes
  service:
    name: elasticsearch
    state: started
    enabled: yes

# Kibana Installation Starts here ---------------------------------
#
- name: Install the kibana
  become: yes
  yum:
    name: kibana
    update_cache: yes

- name: Update the config file to allow outside access in kibana
  become: yes
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: '#server.host:'
    line: 'server.host: "127.0.0.1"'

- name: Defining the server port in kibana
  become: yes
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: '#server.port: 5601'
    line: 'server.port: 5601'

- name: Defining the elasticsearch URL
  become: yes
  lineinfile:
    destfile: /etc/kibana/kibana.yml
    regexp: 'elasticsearch.url:'
    line: 'elasticsearch.url: ["http://localhost:9200"]'

- name: Start the kibana services
  become: yes
  service:
    name: kibana
    state: started
    enabled: yes

- name: Restart the kibana
  become: yes
  service:
    name: kibana
    state: restarted
