---
# tasks file for roles/ubuntu/installvsftpd


- name: Install vsftpd for Ubuntu
  become: yes
  apt:
    name: vsftpd
    state: latest
    update_cache: yes

- name: Change the state of the uncomplicated firewall (UFW)
  become: yes
  service:
    name: ufw
    state: stopped
    enabled: no

- name: Start the vsftpd service
  become: yes
  service:
    name: vsftpd
    state: started
    enabled: yes
