---
# tasks file for roles/opensuse/installvsftpd

- name: Install vsftpd service in opensuse
  become: yes
  zypper:
    name: vsftpd
    state: latest
    update_cache: yes

- name: Change the state firewall (firewalld)
  become: yes
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Start the vsftpd service in opensuse
  become: yes
  service:
    name: vsftpd
    state: started
    enabled: yes
