---
# Tasks for ubuntu (Final - Exam)
- name: Include config yaml
  hosts: all
  tasks:
    - name: include the config
      include_vars:
        file: config.yaml

- name: Change motd for centos and opensuse hosts
  become: yes
  hosts:
    - centos
    - opensuse
  tasks:
    - name: Motd modified
      lineinfile:
        path: /etc/motd
        line: Ansible Managed by '{{ username }}'

- name: Change motd for ubuntu
  hosts: debian
  tasks:
    - name: Motd modified
      become: yes
      command: sh -c 'echo "Ansible Managed by {{ username }}"> /etc/motd'

- name: Pre-requisite to install in Ubuntu
  hosts: debian
  roles:
    - debian/prelimclone
    - debian/installvsftpd
    - debian/configvsftpd
    - debian/installnagios
    - debian/confignagios

- name: Pre-requisite to install in centos
  hosts: centos
  roles:
    - centos/prelimclone
    - centos/installvsftpd
    - centos/configvsftpd
    - centos/installnagios
    - centos/confignagios

- name: Pre-requisite to install in Opensuse
  hosts: opensuse
  roles:
    - opensuse/prelimclone
    - opensuse/installvsftpd
    - opensuse/configvsftpd
    - opensuse/installnagios
    - opensuse/confignagios
