---
# tasks file for roles/centos/installvsftpd

- name: Install vsftpd
  become: yes
  yum:
    name: vsftpd
    state: latest
    update_cache: yes

- name: Change state of firewall
  become: yes
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Create ftp user
  become: yes
  user:
    name: '{{ ftpuser }}'
    password: '{{ ftppass }}'
    comment: "Ftp user"
