---
# tasks file for roles/centos-setup

  - name: Install vsftpd
    become: yes
    yum:
      name: vsftpd
      state: latest
      update_cache: yes

  - name: Change state of firewall
    become: yes
    service:
      name: firewalld
      state: stopped
      enabled: no

  - name: Create ftp user
    become: yes
    user:
      name: gjgerandoy-ftp
      password: $6$XpgcH82y7l7b5pEE$NtQSaBHtDPczwmsRF2qHr0rUkCS30DwvXedjl026itGgzDrrcTRo900Fj.uwsCh8hDRTE1s0U57YX9QIZJvSI/
      comment: "Ftp User"

  - name: Add DenyUser
    become: yes
    lineinfile:
      path: /etc/ssh/sshd_config
      line: "DenyUsers gjgerandoy-ftp"
    register: sshd_config

  - name: Restart SSHD Service
    become: yes
    service:
      name: sshd
      state: restarted
    when: sshd_config.changed

  - name: Create ftp dir
    become: yes
    file:
      path: /home/gjgerandoy-ftp/ftp
      state: directory
      owner: gjgerandoy-ftp
      group: gjgerandoy-ftp
      mode: '0555'

  - name: Create files dir
    become: yes
    file:
      path: /home/gjgerandoy-ftp/ftp/files
      state: directory
      owner: gjgerandoy-ftp
      group: gjgerandoy-ftp

  - name: copy vsftpd.conf
    become: yes
    copy:
      src: vsftpd.conf
      dest: /etc/vsftpd.conf
    register: vsftpd_config

  - name: restart vsftpd
    become: yes
    service:
      name: vsftpd
      state: restarted
    when: vsftpd_config.changed
